#!/bin/sh
set -e

# OLD_DIR=`pwd`
# cd frontend && npm run prod
# cd "$OLD_DIR"

go generate code/server/service/*.go
go build -o bin/bunker-svr code/server/*.go
go build -o bin/bunker code/agent/*.go