// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: bunker.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BunkerClient is the client API for Bunker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BunkerClient interface {
	RunShell(ctx context.Context, in *RunShellRequest, opts ...grpc.CallOption) (*RunShellResponse, error)
}

type bunkerClient struct {
	cc grpc.ClientConnInterface
}

func NewBunkerClient(cc grpc.ClientConnInterface) BunkerClient {
	return &bunkerClient{cc}
}

func (c *bunkerClient) RunShell(ctx context.Context, in *RunShellRequest, opts ...grpc.CallOption) (*RunShellResponse, error) {
	out := new(RunShellResponse)
	err := c.cc.Invoke(ctx, "/Bunker/RunShell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BunkerServer is the server API for Bunker service.
// All implementations must embed UnimplementedBunkerServer
// for forward compatibility
type BunkerServer interface {
	RunShell(context.Context, *RunShellRequest) (*RunShellResponse, error)
	mustEmbedUnimplementedBunkerServer()
}

// UnimplementedBunkerServer must be embedded to have forward compatible implementations.
type UnimplementedBunkerServer struct {
}

func (UnimplementedBunkerServer) RunShell(context.Context, *RunShellRequest) (*RunShellResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunShell not implemented")
}
func (UnimplementedBunkerServer) mustEmbedUnimplementedBunkerServer() {}

// UnsafeBunkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BunkerServer will
// result in compilation errors.
type UnsafeBunkerServer interface {
	mustEmbedUnimplementedBunkerServer()
}

func RegisterBunkerServer(s grpc.ServiceRegistrar, srv BunkerServer) {
	s.RegisterService(&Bunker_ServiceDesc, srv)
}

func _Bunker_RunShell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunShellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BunkerServer).RunShell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Bunker/RunShell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BunkerServer).RunShell(ctx, req.(*RunShellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Bunker_ServiceDesc is the grpc.ServiceDesc for Bunker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bunker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Bunker",
	HandlerType: (*BunkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunShell",
			Handler:    _Bunker_RunShell_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bunker.proto",
}
